version: '3.4'
services:
  db:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: